version: 0.0
os: linux
files: 
  - source: code
    destination: /var/www/html/
hooks: 
  BeforeInstall: 
    - location: scripts/beforeinstall.sh 
      timeout: 300 
      runas: root 
  AfterInstall: 
     - location: scripts/afterinstall.sh 
       timeout: 300 
       runas: root 

